import { Scale } from "lucide-react";
import { Link } from "react-router-dom";

const Terms = () => (
  <div className="mx-auto max-w-3xl px-4 py-16">
    <h1 className="font-heading text-3xl font-bold">Terms of Service</h1>
    <p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString("en-IN")}</p>

    <div className="mt-10 space-y-8 text-sm leading-relaxed text-muted-foreground">
      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">1. Acceptance of Terms</h2>
        <p>By accessing and using NyayaAI, you agree to be bound by these Terms of Service. If you do not agree, please do not use our platform.</p>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">2. Nature of Service</h2>
        <p className="font-medium text-foreground">Important Disclaimer:</p>
        <p className="mt-1">NyayaAI provides <strong>general legal information</strong> using artificial intelligence. Our platform does <strong>NOT</strong> provide legal advice, and using NyayaAI does not create an attorney-client relationship. The information provided should not be used as a substitute for consultation with a qualified legal professional.</p>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">3. AI-Generated Content</h2>
        <ul className="ml-4 list-disc space-y-1">
          <li>All responses and documents are generated by artificial intelligence</li>
          <li>AI-generated content may contain errors or outdated information</li>
          <li>Users are responsible for verifying all information with qualified professionals</li>
          <li>Generated documents are drafts and may require legal review before use</li>
        </ul>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">4. User Responsibilities</h2>
        <ul className="ml-4 list-disc space-y-1">
          <li>You will not use NyayaAI for any unlawful purpose</li>
          <li>You understand that AI responses are informational, not legal advice</li>
          <li>You will verify critical legal information with a licensed lawyer</li>
          <li>You will not rely solely on NyayaAI for legal decisions</li>
        </ul>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">5. Limitation of Liability</h2>
        <p>NyayaAI, its creators, and affiliates shall not be liable for any damages arising from the use or inability to use our platform. This includes but is not limited to direct, indirect, incidental, or consequential damages resulting from reliance on AI-generated information.</p>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">6. Intellectual Property</h2>
        <p>The NyayaAI platform, including its design, features, and content, is protected by intellectual property laws. Users may download generated documents for personal use only.</p>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">7. Modifications</h2>
        <p>We reserve the right to modify these Terms at any time. Continued use of the platform after changes constitutes acceptance of the updated Terms.</p>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">8. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India.</p>
      </section>

      <section>
        <h2 className="mb-3 font-heading text-lg font-bold text-foreground">9. Contact</h2>
        <p>For questions about these Terms, contact us at <span className="font-medium text-primary">legal@nyayaai.in</span></p>
      </section>
    </div>

    <div className="mt-12 rounded-xl border bg-muted/50 p-4 text-center text-xs text-muted-foreground">
      This platform provides general legal information and does not constitute legal advice. Please consult a qualified lawyer.
    </div>
  </div>
);

export default Terms;
